Loading gpytorch/gpu-cuda-11.6/pytorch-1.11.0/1.8.0
  Loading requirement: cudnn/8.4.1 pytorch/gpu-cuda-11.6/1.11.0
ERROR: Could not find a version that satisfies the requirement scipy.stats (from versions: none)
ERROR: No matching distribution found for scipy.stats
ERROR: Could not find a version that satisfies the requirement scipy.interpolate (from versions: none)
ERROR: No matching distribution found for scipy.interpolate
ERROR: Could not find a version that satisfies the requirement itertools (from versions: none)
ERROR: No matching distribution found for itertools
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchtext 0.15.1a0+e2b27f9 requires torchdata, which is not installed.
pyro-ppl 1.8.1 requires opt-einsum>=2.3.2, but you have opt-einsum 0+unknown which is incompatible.
ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os
Traceback (most recent call last):
  File "/raven/u/dvoss/al_pmssmwithgp/model/TwoCirclesnD.py", line 925, in <module>
    run_pipeline_with_active_learning(args)
  File "/raven/u/dvoss/al_pmssmwithgp/model/TwoCirclesnD.py", line 881, in run_pipeline_with_active_learning
    gp_pipeline = GPModelPipeline(
  File "/raven/u/dvoss/al_pmssmwithgp/model/TwoCirclesnD.py", line 74, in __init__
    self.load_initial_data()
  File "/raven/u/dvoss/al_pmssmwithgp/model/TwoCirclesnD.py", line 82, in load_initial_data
    self.y_train = torch.tensor(self.truth0(self.x_train), dtype=torch.float32).to(self.device)
  File "/raven/u/dvoss/al_pmssmwithgp/model/TwoCirclesnD.py", line 66, in <lambda>
    two_gaussians = lambda X: gauss1(X) + gauss2(X)
  File "/raven/u/dvoss/al_pmssmwithgp/model/TwoCirclesnD.py", line 64, in <lambda>
    gauss1 = lambda X: np.atleast_1d(multivariate_normal.pdf(X, mean=mean1, cov=cov1))
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.11/lib/python3.9/site-packages/scipy/stats/_multivariate.py", line 515, in pdf
    x = self._process_quantiles(x, dim)
  File "/mpcdf/soft/SLE_15/packages/x86_64/anaconda/3/2021.11/lib/python3.9/site-packages/scipy/stats/_multivariate.py", line 430, in _process_quantiles
    x = np.asarray(x, dtype=float)
  File "/mpcdf/soft/SLE_15/packages/skylake/pytorch/gpu-cuda-11.6/anaconda_3_2021.11-2021.11/1.11.0/lib/python3.9/site-packages/torch/_tensor.py", line 734, in __array__
    return self.numpy().astype(dtype, copy=False)
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
srun: error: ravg1200: task 0: Exited with exit code 1
srun: Terminating StepId=15081227.0
