Loading gpytorch/gpu-cuda-11.6/pytorch-1.11.0/1.8.0
  Loading requirement: cudnn/8.4.1 pytorch/gpu-cuda-11.6/1.11.0
Traceback (most recent call last):
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 232, in <module>
    gp_pipeline.train_model(iters=1000)
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 67, in train_model
    self.best_model, self.losses, self.losses_valid = self.model.do_train_loop(iters=iters, train_x=self.x_train, train_y=self.y_train)
TypeError: do_train_loop() got an unexpected keyword argument 'train_x'
srun: error: ravg1070: task 0: Exited with exit code 1
srun: Terminating StepId=12180799.0
