Loading gpytorch/gpu-cuda-11.6/pytorch-1.11.0/1.8.0
  Loading requirement: cudnn/8.4.1 pytorch/gpu-cuda-11.6/1.11.0
Traceback (most recent call last):
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1D.py", line 312, in <module>
    gp_pipeline = GPModelPipeline(csv_file='M_2_fixed.csv', output_dir=output_dir)
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1D.py", line 204, in __init__
    self.initialize_model()
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1D.py", line 232, in initialize_model
    self.model = MultitaskGP(self.x_train, self.y_train, self.x_valid, self.y_valid, self.likelihood)
  File "/raven/u/dvoss/al_pmssmwithgp/model/multitaskGP.py", line 134, in __init__
    self.covar_module.lengthscale = torch.tensor([0.5e-2])
  File "/mpcdf/soft/SLE_15/packages/skylake/pytorch/gpu-cuda-11.6/anaconda_3_2021.11-2021.11/1.11.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1233, in __setattr__
    object.__setattr__(self, name, value)
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/kernels/kernel.py", line 255, in lengthscale
    self._set_lengthscale(value)
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/kernels/kernel.py", line 264, in _set_lengthscale
    self.initialize(raw_lengthscale=self.raw_lengthscale_constraint.inverse_transform(value))
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/constraints/constraints.py", line 140, in inverse_transform
    raise RuntimeError(
RuntimeError: Cannot make an Interval directly with non-finite bounds. Use a derived class like GreaterThan or LessThan instead.
srun: error: ravg1147: task 0: Exited with exit code 1
srun: Terminating StepId=12129438.0
